################################################################################
#
#  Running Health Models in R
#
#  Script 01 - First-stage time-series models by IGR
#
################################################################################

#------------------------------------------------------------------------------
# Purpose
#------------------------------------------------------------------------------
#
# This script fits first-stage time-series models separately for each
# Immediate Geographic Region (IGR) in Rio de Janeiro.
#
# The aim is to estimate the IGR-specific temperature-mortality association
# using a Distributed Lag Non-Linear Model (DLNM).
#
# In this material, we adopt a fixed model specification:
#
#   - maximum lag: 5 days
#   - temperature-response: natural cubic spline with two internal knots
#     located at the 10th and 90th percentiles
#   - lag-response: natural cubic spline with three log-spaced knots
#   - seasonal and long-term adjustment: natural spline with 4 degrees of
#     freedom per year
#
# In addition to saving the first-stage coefficients for the second-stage
# meta-analysis, this script also produces simple outputs:
#
#   - Minimum Mortality Temperature (MMT) by IGR
#   - RR at the 1st and 99th local temperature percentiles
#   - risk surface for one selected IGR
#   - lag-specific and cumulative exposure-response curves
#   - exposure-response curves for all IGRs
#
################################################################################


#==============================================================================
# 1. Output folders
#==============================================================================

# All outputs generated by this script will be saved in the "results" folder.
# Figures will be saved in a separate subfolder.

dir_save <- "results"
dir_fig  <- file.path(dir_save, "figures")

if (!dir.exists(dir_save)) {
  dir.create(dir_save)
}

if (!dir.exists(dir_fig)) {
  dir.create(dir_fig)
}


#==============================================================================
# 2. Load and prepare data
#==============================================================================

# Mortality and temperature data have already been aggregated at the
# Immediate Geographic Region (IGR) level. Both datasets contain one
# observation per IGR and calendar day.

# Load mortality data
mort_data <- read_parquet("mort_data_RJ.parquet")

# Load daily mean temperature data
tempdata <- read_parquet("tempdata_RJ.parquet")


# Merge mortality and temperature datasets using the IGR identifier
# and calendar date.

data_final <- inner_join(
  x  = mort_data,
  y  = tempdata,
  by = c("IGR", "Date")
)


# Prepare variables required for the time-series analysis.
#
# The day of the week is included as a categorical variable to adjust
# for systematic weekly patterns in mortality. A sequential time index
# is also created within each IGR and will later be used to control
# for long-term and seasonal trends.

data_final <- data_final |>
  mutate(
    Date = as.Date(Date),
    
    dow = factor(
      weekdays(Date),
      levels = c(
        "Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday"
      )
    )
  ) |>
  arrange(IGR, Date) |>
  group_by(IGR) |>
  mutate(
    time = row_number()
  ) |>
  ungroup()


#==============================================================================
# 3. Define model specification
#==============================================================================

# Name of the temperature variable used in the model.

temp_var <- "daily_pop_weighted_mean_temperature"


# Maximum lag in days.
# Here we use 5 days because heat-related mortality effects are usually
# concentrated in the first few days after exposure.

lag_num <- 5


# Natural cubic splines are used for both dimensions of the DLNM:
#
#   - the temperature-response dimension
#   - the lag-response dimension

lagfun <- "ns"
varfun <- "ns"


# Internal knots for the temperature-response curve.
# These are defined as percentiles of the local temperature distribution
# within each IGR.

knots_perc <- c(0.10, 0.90)


# Internal knots for the lag-response curve.
# Log-spaced knots give more flexibility at shorter lags, where the effect
# of heat is expected to change more rapidly.

knots_lag <- logknots(lag_num, nk = 3)


# Degrees of freedom per year for long-term and seasonal control.

dfseas <- 4


# Number of coefficients expected after reducing the DLNM to the overall
# cumulative temperature-mortality association.

num_cols <- length(knots_perc) + 1


# IGRs included in the analysis.

igr_include <- unique(data_final$IGR)


# Common temperature range used as boundary for the spline basis.
# This helps keep the basis definition comparable across IGRs.

bound_temp <- range(
  data_final[[temp_var]],
  na.rm = TRUE
)


# IGR used to illustrate the risk surface and selected curves.
# For the course, we use the first IGR in the dataset. This can be replaced
# by any IGR code available in igr_include.

igr_example <- "330001"


# Lag selected for the lag-specific exposure-response curve.

lag_example <- 0


#==============================================================================
# 4. Create objects to store first-stage results
#==============================================================================

# Matrix to store the reduced coefficients for each IGR.

coefs_all_mat <- matrix(
  NA,
  nrow = length(igr_include),
  ncol = num_cols,
  dimnames = list(igr_include, NULL)
)


# List to store the variance-covariance matrix of the reduced coefficients
# for each IGR.

vcov_all <- setNames(
  vector("list", length(igr_include)),
  igr_include
)


# Vector to store the Minimum Mortality Temperature estimated in each IGR.

MMT_vec <- rep(NA, length(igr_include))


# Vectors to store relative risks at the 1st and 99th percentiles of the
# local IGR-specific temperature distribution.

P1_vec  <- rep(NA, length(igr_include))
P99_vec <- rep(NA, length(igr_include))

RR_P1_vec  <- rep(NA, length(igr_include))
RR_P99_vec <- rep(NA, length(igr_include))


# List to store cumulative exposure-response curves for all IGRs.

erf_all <- vector("list", length(igr_include))
names(erf_all) <- igr_include


# Objects used only for the selected example IGR.

risk_surface_example <- NULL
lag_curve_example    <- NULL
cum_curve_example    <- NULL


#==============================================================================
# 5. Stage 1 - Fit IGR-specific time-series models
#==============================================================================

# The first stage consists of fitting an independent time-series model for
# each Immediate Geographic Region (IGR).
#
# The following steps are repeated for every IGR:
#
#   1. Subset the data for the current IGR.
#   2. Construct the DLNM cross-basis.
#   3. Fit the quasi-Poisson regression model.
#   4. Estimate the Minimum Mortality Temperature (MMT).
#   5. Re-predict the association centred at the MMT.
#   6. Reduce the bi-dimensional association to the cumulative curve.
#   7. Store coefficients, covariance matrices, MMT and selected RRs.
#   8. Store curves for later plotting.
#
# The reduced coefficients and covariance matrices will be used later in the
# second-stage multivariate meta-analysis.

for (i in seq_along(igr_include)) {
  
  igr_code <- igr_include[i]
  
  cat("Fitting IGR", i, "of", length(igr_include),
      "- IGR:", igr_code, "\n")
  
  
  #----------------------------------------------------------------------
  # Step 1. Extract data for the current IGR
  #----------------------------------------------------------------------
  
  data_igr <- data_final[data_final$IGR == igr_code, ]
  
  
  # Number of years available for this IGR.
  # This determines the total degrees of freedom used for seasonal and
  # long-term trend adjustment.
  
  n_years <- length(unique(format(data_igr$Date, "%Y")))
  
  
  #----------------------------------------------------------------------
  # Step 2. Construct the DLNM cross-basis
  #----------------------------------------------------------------------
  
  # The temperature knots are defined using the local temperature
  # distribution of each IGR.
  
  knots_temp <- quantile(
    data_igr[[temp_var]],
    probs = knots_perc,
    na.rm = TRUE
  )
  
  
  # The cross-basis combines:
  #
  #   - the non-linear association with temperature;
  #   - the delayed association across lag days.
  
  cb <- crossbasis(
    data_igr[[temp_var]],
    lag = lag_num,
    argvar = list(
      fun   = varfun,
      knots = knots_temp,
      Bound = bound_temp
    ),
    arglag = list(
      fun   = lagfun,
      knots = knots_lag
    )
  )
  
  
  #----------------------------------------------------------------------
  # Step 3. Fit the first-stage time-series model
  #----------------------------------------------------------------------
  
  # The model uses a quasi-Poisson family for daily mortality counts and
  # adjusts for day of the week and smooth long-term/seasonal trends.
  
  model <- glm(
    count_all ~ cb + dow + ns(time, df = dfseas * n_years),
    family = quasipoisson(),
    data = data_igr
  )
  
  
  #----------------------------------------------------------------------
  # Step 4. Identify the Minimum Mortality Temperature
  #----------------------------------------------------------------------
  
  # First, we predict the cumulative exposure-response association without
  # centering. The MMT is the temperature with the lowest predicted
  # cumulative relative risk.
  
  pred_uncentered <- crosspred(
    cb,
    model,
    by = 0.1
  )
  
  MMT <- pred_uncentered$predvar[
    which.min(pred_uncentered$allRRfit)
  ]
  
  MMT_vec[i] <- MMT
  
  
  #----------------------------------------------------------------------
  # Step 5. Predict the association centred at the MMT
  #----------------------------------------------------------------------
  
  # Once the MMT is identified, we centre the predictions at the MMT.
  # This means that RR = 1 at the MMT.
  
  pred <- crosspred(
    cb,
    model,
    by = 0.1,
    cen = MMT
  )
  
  
  #----------------------------------------------------------------------
  # Step 6. Reduce the DLNM association
  #----------------------------------------------------------------------
  
  # The cross-basis is reduced to the overall cumulative exposure-response
  # association across all lags. This reduced curve is the input for the
  # second-stage meta-analysis.
  
  red <- crossreduce(
    cb,
    model,
    by = 0.1,
    type = "overall",
    cen = MMT
  )
  
  
  #----------------------------------------------------------------------
  # Step 7. Store first-stage estimates
  #----------------------------------------------------------------------
  
  coefs_all_mat[i, ] <- coef(red)
  vcov_all[[i]] <- vcov(red)
  
  
  #----------------------------------------------------------------------
  # Step 8. Store RR at P1 and P99
  #----------------------------------------------------------------------
  
  # We calculate the 1st and 99th percentiles of the local temperature
  # distribution and extract the corresponding relative risks from the
  # cumulative exposure-response curve.
  
  P1  <- quantile(data_igr[[temp_var]], 0.01, na.rm = TRUE)
  P99 <- quantile(data_igr[[temp_var]], 0.99, na.rm = TRUE)
  
  P1_vec[i]  <- P1
  P99_vec[i] <- P99
  
  idx_p1 <- which.min(abs(pred$predvar - P1))
  idx_p99 <- which.min(abs(pred$predvar - P99))
  
  RR_P1_vec[i]  <- pred$allRRfit[idx_p1]
  RR_P99_vec[i] <- pred$allRRfit[idx_p99]
  
  
  #----------------------------------------------------------------------
  # Step 9. Store cumulative ERF for this IGR
  #----------------------------------------------------------------------
  
  # The cumulative exposure-response function is stored in long format
  # to simplify plotting after the loop.
  
  erf_all[[i]] <- data.frame(
    IGR         = igr_code,
    Temperature = pred$predvar,
    RR          = pred$allRRfit,
    RR_low      = pred$allRRlow,
    RR_high     = pred$allRRhigh,
    MMT         = MMT,
    P1          = P1,
    P99         = P99,
    stringsAsFactors = FALSE
  )
  
  #----------------------------------------------------------------------
  # Step 10. Store additional outputs for one example IGR
  #----------------------------------------------------------------------
  
  # we store some outputs:
  #
  #   - the full temperature-lag risk surface;
  #   - the exposure-response curve at one selected lag;
  #   - the cumulative exposure-response curve across all lags.
  #
  # These outputs help illustrate how the DLNM represents risk in both
  # dimensions: temperature and lag.
  
  if (igr_code == igr_example) {
    
    # Risk surface
    
    risk_surface_example <- as.data.frame(
      as.table(pred$matRRfit)
    )
    
    names(risk_surface_example) <- c("Temperature", "Lag", "RR")
    
    risk_surface_example <- risk_surface_example |>
      mutate(
        IGR = igr_code,
        Temperature = as.numeric(as.character(Temperature)),
        Lag = as.numeric(as.character(str_sub(Lag,4,4)))
      )
    
    
    # Lag-specific exposure-response curve
    
    lag_names <- colnames(pred$matRRfit)
    lag_id <- which.min(abs(as.numeric(str_sub(lag_names,4,4)) - lag_example))
    
    lag_curve_example <- data.frame(
      IGR         = igr_code,
      Lag         = as.numeric(str_sub(lag_names[lag_id],4,4)),
      Temperature = pred$predvar,
      RR          = pred$matRRfit[, lag_id],
      RR_low      = pred$matRRlow[, lag_id],
      RR_high     = pred$matRRhigh[, lag_id],
      stringsAsFactors = FALSE
    )
    
    
    # Cumulative exposure-response curve
    
    cum_curve_example <- data.frame(
      IGR         = igr_code,
      Temperature = pred$predvar,
      RR          = pred$allRRfit,
      RR_low      = pred$allRRlow,
      RR_high     = pred$allRRhigh,
      MMT         = MMT,
      stringsAsFactors = FALSE
    )
  }
}


#==============================================================================
# 6. Organise first-stage summary
#==============================================================================

# Create a summary table with the estimated MMT and selected relative risks
# for each IGR.

results_igr <- data.frame(
  IGR    = igr_include,
  MMT    = MMT_vec,
  P1     = P1_vec,
  RR_P1  = RR_P1_vec,
  P99    = P99_vec,
  RR_P99 = RR_P99_vec,
  stringsAsFactors = FALSE
)

head(results_igr)


# Combine all IGR-specific cumulative exposure-response curves.

erf_all_df <- bind_rows(erf_all)

#----------------------------------------------------------------------
# Step 7. Plot 3D exposure-lag-response surface for one example IGR
#----------------------------------------------------------------------

# For one selected IGR, we plot the full exposure-lag-response surface.
# This graph is built directly from the DLNM predictions stored in `pred`.
#
# The axes represent:
#
#   - temperature: exposure dimension;
#   - lag: delayed effect dimension;
#   - RR: relative risk centred at the IGR-specific MMT.
#

  plot(
    pred,
    ptype = "3d",
    xlab = "Temperature (°C)",
    ylab = "Lag",
    zlab = "RR",
    main = paste0("Exposure-lag-response - IGR ", igr_example),
    theta = 230,
    phi = 35,
    ltheta = 170,
    shade = 0.4,
    border = "black",
    col = "lightblue",
    ticktype = "detailed"
  )
  
#==============================================================================
# 9. Plot lag-specific exposure-response curve for one example IGR
#==============================================================================

# This graph shows the exposure-response association at a single lag.
# It helps illustrate that the heat effect can vary across lag days.

p_lag <- ggplot(
  lag_curve_example,
  aes(x = Temperature, y = RR)
) +
  geom_ribbon(
    aes(ymin = RR_low, ymax = RR_high),
    alpha = 0.20
  ) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = 1, linetype = 2) +
  labs(
    title = paste0(
      "Lag-specific exposure-response curve - IGR ",
      igr_example,
      ", lag ",
      unique(lag_curve_example$Lag)
    ),
    x = "Temperature (°C)",
    y = "Relative Risk"
  ) +
  theme_classic()

p_lag

ggsave(
  filename = file.path(dir_fig, "example_IGR_lag_specific_curve.png"),
  plot = p_lag,
  width = 7,
  height = 5,
  dpi = 300
)


#==============================================================================
# 10. Plot cumulative exposure-response curve for one example IGR
#==============================================================================

# The cumulative curve summarizes the total temperature-related risk across
# all lag days included in the DLNM.

p_cum <- ggplot(
  cum_curve_example,
  aes(x = Temperature, y = RR)
) +
  geom_ribbon(
    aes(ymin = RR_low, ymax = RR_high),
    alpha = 0.20
  ) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_vline(
    xintercept = unique(cum_curve_example$MMT),
    linetype = 3
  ) +
  labs(
    title = paste0("Cumulative exposure-response curve - IGR ", igr_example),
    x = "Temperature (°C)",
    y = "Cumulative Relative Risk"
  ) +
  theme_classic()

p_cum

ggsave(
  filename = file.path(dir_fig, "example_IGR_cumulative_curve.png"),
  plot = p_cum,
  width = 7,
  height = 5,
  dpi = 300
)


#==============================================================================
# 11. Plot cumulative ERFs for all IGRs
#==============================================================================

# This panel compares the cumulative exposure-response functions estimated
# for all IGRs. Each curve is centred at its own IGR-specific MMT.

p_all_erf <- ggplot(
  erf_all_df,
  aes(x = Temperature, y = RR)
) +
  geom_ribbon(
    aes(ymin = RR_low, ymax = RR_high),
    alpha = 0.15
  ) +
  geom_line(linewidth = 0.8) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_vline(
    aes(xintercept = MMT),
    linetype = 3
  ) +
  facet_wrap(~ IGR, scales = "free_x") +
  labs(
    title = "Cumulative exposure-response functions by IGR",
    x = "Temperature (°C)",
    y = "Cumulative Relative Risk"
  ) +
  theme_classic()

p_all_erf

ggsave(
  filename = file.path(dir_fig, "all_IGR_cumulative_ERFs.png"),
  plot = p_all_erf,
  width = 12,
  height = 8,
  dpi = 300
)


#==============================================================================
# 12. Save first-stage results
#==============================================================================

# Objects are saved separately instead of saving the full R environment.
# This makes the workflow more transparent and easier to reproduce.

saveRDS(
  coefs_all_mat,
  file = file.path(dir_save, "first_stage_coefficients.rds")
)

saveRDS(
  vcov_all,
  file = file.path(dir_save, "first_stage_vcov.rds")
)

saveRDS(
  igr_include,
  file = file.path(dir_save, "igr_include.rds")
)

saveRDS(
  erf_all_df,
  file = file.path(dir_save, "first_stage_ERF_all_IGR.rds")
)

write.csv(
  results_igr,
  file = file.path(dir_save, "first_stage_summary_by_IGR.csv"),
  row.names = FALSE
)

write.csv(
  erf_all_df,
  file = file.path(dir_save, "first_stage_ERF_all_IGR.csv"),
  row.names = FALSE
)

write.csv(
  risk_surface_example,
  file = file.path(dir_save, "example_IGR_risk_surface.csv"),
  row.names = FALSE
)

write.csv(
  lag_curve_example,
  file = file.path(dir_save, "example_IGR_lag_specific_curve.csv"),
  row.names = FALSE
)

write.csv(
  cum_curve_example,
  file = file.path(dir_save, "example_IGR_cumulative_curve.csv"),
  row.names = FALSE
)

################################################################################
# End of script
################################################################################

